<?xml version='1.0' encoding='UTF-8'?>
<package format="2">
  <name>ocs2_sqp</name>
  <version>0.0.0</version>
  <description>The ocs2_hpipm package</description>
  <maintainer email="huier@todo.todo">huier</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_cmake_gtest</depend>
  <depend>ament_lint_auto</depend>
  <depend>blasfeo_ament</depend>
  <depend>hpipm_ament</depend>
  <depend>ocs2_core</depend>
  <depend>ocs2_mpc</depend>
  <depend>ocs2_oc</depend>
  <depend>ocs2_qp_solver</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
